// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/assisted-service/internal/controller/controllers (interfaces: BMOUtils)

// Package controllers is a generated GoMock package.
package controllers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBMOUtils is a mock of BMOUtils interface.
type MockBMOUtils struct {
	ctrl     *gomock.Controller
	recorder *MockBMOUtilsMockRecorder
}

// MockBMOUtilsMockRecorder is the mock recorder for MockBMOUtils.
type MockBMOUtilsMockRecorder struct {
	mock *MockBMOUtils
}

// NewMockBMOUtils creates a new mock instance.
func NewMockBMOUtils(ctrl *gomock.Controller) *MockBMOUtils {
	mock := &MockBMOUtils{ctrl: ctrl}
	mock.recorder = &MockBMOUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBMOUtils) EXPECT() *MockBMOUtilsMockRecorder {
	return m.recorder
}

// ConvergedFlowAvailable mocks base method.
func (m *MockBMOUtils) ConvergedFlowAvailable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvergedFlowAvailable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ConvergedFlowAvailable indicates an expected call of ConvergedFlowAvailable.
func (mr *MockBMOUtilsMockRecorder) ConvergedFlowAvailable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvergedFlowAvailable", reflect.TypeOf((*MockBMOUtils)(nil).ConvergedFlowAvailable))
}

// GetIronicAgentImage mocks base method.
func (m *MockBMOUtils) GetIronicAgentImage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIronicAgentImage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIronicAgentImage indicates an expected call of GetIronicAgentImage.
func (mr *MockBMOUtilsMockRecorder) GetIronicAgentImage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIronicAgentImage", reflect.TypeOf((*MockBMOUtils)(nil).GetIronicAgentImage))
}

// GetIronicServiceURLs mocks base method.
func (m *MockBMOUtils) GetIronicServiceURLs() ([]string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIronicServiceURLs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIronicServiceURLs indicates an expected call of GetIronicServiceURLs.
func (mr *MockBMOUtilsMockRecorder) GetIronicServiceURLs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIronicServiceURLs", reflect.TypeOf((*MockBMOUtils)(nil).GetIronicServiceURLs))
}
